name: Build Status

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        sudo apt-get install graphviz xvfb
        python -m pip install -r requirements.txt
        python -m pip install -e .[dev]
    - name: Test
      run: |
        xvfb-run --auto-servernum make tests
    - name: Coverage
      run: |
        codecov --token f8f2787b-4aa9-4161-8b13-88ddde282d57
